### ISSUE TITLE
About the original code of the Unet Gan

### ISSUE THREAD

**Issue by p0werHu** [lucidrains/unet-stylegan2#2]
Hi,
Thanks for your excellent work. I want to consult whether you have the original official code of the Unet Gan
Because I didn't found the Github link in their paper and cannot find it on the Github

Thanks

**Comment by lucidrains** [comment]
Hi! I don't think they ever released it :(

**Comment by edgarschnfld** [comment]
It's here https://github.com/boschresearch/unetgan 🙂
