### ISSUE TITLE
Implement Pytorch's built-in AMP instead of APEX

### ISSUE THREAD

**Issue by n00mkrad** [lucidrains/unet-stylegan2#4]
Hello, would it be possible to utilize Pytorch 1.6.0's AMP for mixed precision training instead of APEX?

It would be easier to use, and I personally haven't managed to get APEX working.

**Comment by lucidrains** [comment]
@n00mkrad Hi Noomkrad! I'm trying to avoid Apex until there's more adoption of Pytorch 1.6. Using their AMP would mean forcing everyone to upgrade!
