### ISSUE TITLE
Mode collapse with Flowers dataset

### ISSUE THREAD

**Issue by matthewchung74** [lucidrains/unet-stylegan2#7]
Hi, first thanks for writing this! I'm trying to replicate your flowers results within colab.

I'm getting mode collapse with the flowers dataset: http://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz
sample image:
https://drive.google.com/file/d/12vbFGqi8Rj3CLYYRYqMsQUezS-NgcgEC/view?usp=sharing

I am getting crazy numbers for D and G loss, but there was an abrupt change around 30k steps.
all the output values are at the bottom of this https://gist.github.com/foobar8675/affbb99eead9cf61dffc396bf4c8a6ea

I am using the default parameters from `def train_from_folder(` but am definitely missing something!  I was wondering if you can share what input parameters you are using for the flowers dataset?

(I copied and pasted the project into colab)
https://github.com/foobar8675/ml_experiments/blob/47c04a05e3ec9d9848d14256d41d99318b350742/stylegan2_pytorch.ipynb

Do you have any suggestions?

**Comment by zimonitrome** [comment]
Hey did you end up solving this?

All your links seem broken.

**Comment by matthewchung74** [comment]
i did not and went back to his lucid's other stylegan repo, which worked fine.
